config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  mount ActionCable.server => '/cable'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

  protected
  def resource_not_found
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all.order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article has been created.'
      redirect_to articles_path
    else
      flash.now[:danger] = 'Article has not been created.'
      render :new
    end

  end


  def show
    @comment = @article.comments.build
    @comments = @article.comments
  end

  def edit
    unless @article.user == current_user
      flash[:alert] = 'You can only edit your own articles.'
      redirect_to root_path
    end
  end


  def update
    unless @article.user == current_user
      flash[:danger] = 'You can only edit your own articles.'
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:success] = 'Article has been updated'
        redirect_to @article
      else
        flash.now[:danger] = 'Article has not been updated'
        render :edit
      end

    end

  end

  def destroy

    if @article.destroy
      flash[:success] = 'Article has been deleted'
      redirect_to articles_path
    end
  end

  protected

  def resource_not_found
    message = 'The article you are looking for could not be found'
    flash[:alert] = message

    redirect_to root_path
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_article

  def create
    unless current_user
      flash[:alert] = 'Please sign in or sign up first'
      redirect_to new_user_session_path
    else
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user


      if @comment.save
        #as soon as it saves brodcast it everywhere
        ActionCable.server.broadcast "comments",
                                     render(partial: 'comments/comment', object: @comment )
        flash[:notice] = 'Comment has been created'
      else
        flash.now[:alert] = 'Comment has not been created'
      end
      #redirect_to article_path(@article)
    end
  end

  #update to server  go to developement .rb
  def index

  end

  def show

  end

  def edit

  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def persisted_comments(comments)
    #we only want that are coming from the database
    comments.reject{ |comment| comment.new_record?}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, html: {class: "form-horizontal", role: "form"}) do |f| %>

        <% if @article.errors.any? %>
            <div class="panel panel-danger col-md-offfset-1">

              <div class="panel-heading">

                <h2 class="panel-title">
                  <%= pluralize(@article.errors.count, 'error') %>
                  prohibited this article from getting created:
                </h2>

                <div class="panel-body">
                  <ul>
                    <% @article.errors.full_messages.each do |msg| %>
                        <li>
                          <%= msg %>
                        </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>


        <% end %>

        <div class="form-group">
          <div class="control-label col-md-1">
            <%= f.label :title %>
          </div>
          <div class="col-md-10">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title of Article', autofocus: true %>
          </div>
        </div>


        <div class="form-group">
          <div class="control-label col-md-1">
            <%= f.label :body %>
          </div>
          <div class="col-md-10">
            <%= f.text_area :body, rows: 15, class: 'form-control', placeholder: 'Body of Article'%>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-offset-1 col-md-11">
            <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center">Editing an Article</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%=  link_to 'New Article', new_article_path, class: 'btn btn-default btn-large', id: 'new-article-btn' %>
<% end %>


<% if @articles.blank?%>
    <h1 id="no-articles">
      No articles created
    </h1>
<% else %>
    <% @articles.each do |article| %>
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>

          <div class="article-body">
            <%= truncate(article.body, length: 100) %>
          </div>

          <div class="author">
            <small>Created by: <%= article.user.email %></small>
          </div>
        </div>
    <% end %>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding New Article</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<% if @article.present?%>

    <article class="detail-article">
      <h1 class="article-detail-title">
        <%= @article.title %>
      </h1>


      <div class="glyphicon glyphicon-calendar" id="article-date">
        <%= @article.created_at.strftime("%b %d %Y") %>
      </div>

      <div class="article-body">
        <%= @article.body %>
      </div>

    </article>

      <% if user_signed_in? %>
        <% if current_user == @article.user %>
            <div class="edit-delete">
              <%= link_to 'Edit Article', edit_article_path(@article), class: 'btn btn-primary btn-large btn-space' %>
              <%= link_to 'Delete Article', article_path(@article), method: :delete,
                          data: {confirm: 'Are you sure you want to delete the article.'}, class: 'btn btn-primary btn-large btn-space'
              %>
              </div>
        <% end %>
          <div class="col-md-12">
            <!-- this is for adding comments -->
            <%= form_for [@article, @comment ], remote: true,
                         :html => {class: "form-horizontal", role: "form"} do |f| %>

                <!-- -->
                <!-- if you want to handle the erros that might be generated-->
                <% if @comment.errors.any? %>
                    <div class="panel panel-danger col-md-offset-1">
                      <div class="panel-heading">
                        <h2 class="panel-title">
                          <%= pluralize(@comment.errors.count, 'error') %>
                          prohibited this comment from being saved:
                        </h2>
                        <div class="panel-body">
                          <ul>
                            <% @comment.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <%end%>
                          </ul>
                        </div>
                      </div>
                    </div>
                <% end %>


                <!-- creating the form-->

                <div class="form-group">
                  <div class="control-label col-md-2">
                    <%= f.label :body, 'New Comment' %>
                  </div>
                  <div class="cold-md-7">
                    <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Your comment' %>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-offset-2 cold-md-7">
                    <%= f.submit 'Add Comment', class: 'btn btn-primary btn-lg pull-right' %>
                  </div>
                </div>


            <% end %>
          </div>
      <% end %>

    <div class="col-md-12">
      <header>
        <h2>Comments</h2>
      </header>
      <div class="col-md-6">
        <% if @article.comments.any?%>
            <div id="messages">
              <% persisted_comments(@comments).each do |comment| %>
                  <div class="comment-body">
                    <%= comment.body %>
                  </div>
                  <div class="comment-time">
                    <%= time_ago_in_words(comment.created_at) %>
                    ago by <%= comment.user.email %>
                  </div>
                  <hr>
              <% end %>
            </div>
        <% else %>
            There are no comments to show
        <% end %>
      </div>
    </div>





<% end %>

app/views/comments/_comment.html.erb
<div class="comment-body">
  <%= comment.body %>
</div>
<div class="comment-time">
  <%= time_ago_in_words(comment.created_at) %>
  ago by <%= comment.user.email %>
</div>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/header' %>
  <%= render 'shared/main' %>


  </body>
</html>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button"
                class="navbar-toggle"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1">

          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
      </div>

      <div class="navbar-collpase" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to "Home", root_path %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item"><%= link_to "Sign up", new_user_registration_path %></li>
          <li class="nav-item"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% if user_signed_in? %>
              <div class="navbar-right">
                <p class="navbar-text">
                  Signed in as <%= "#{current_user.email}" %>
                </p>
              </div>
          <% end %>
        </ul>
      </div>



    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% flash.each do |key, message| %>
          <div class="text-center alert alert-<%= key == 'notice'?'success' : 'danger' %>">
            <%= message %>
          </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>